const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, 'Eventify');

function write(filePath, content) {
    const fullPath = path.join(rootDir, filePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content.trim() + '\n', 'utf8');
}

console.log('Atualizando o repositório Eventify com CRUD completo, rotas e validações...');

// ==========================================================
// BACKEND UPDATES
// ==========================================================

write('server/src/db/init.ts', [
    "import { getDB } from './database';",
    "import fs from 'fs';",
    "import path from 'path';",
    "import bcrypt from 'bcryptjs';",
    "const initDB = async () => {",
    "    try {",
    "        const db = await getDB();",
    "        const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf-8');",
    "        await db.exec(schema);",
    "        const users = [",
    "            { name: 'Admin', email: 'admin@eventify.com', pass: 'admin123' },",
    "            { name: 'Gerente', email: 'gerente@eventify.com', pass: 'gerente123' },",
    "            { name: 'Operador', email: 'operador@eventify.com', pass: 'operador123' }",
    "        ];",
    "        for (const u of users) {",
    "            if (!(await db.get('SELECT * FROM users WHERE email = ?', [u.email]))) {",
    "                await db.run('INSERT INTO users (name, email, password) VALUES (?, ?, ?)', [u.name, u.email, await bcrypt.hash(u.pass, 10)]);",
    "            }",
    "        }",
    "        const eventsCount = await db.get('SELECT COUNT(*) as c FROM events');",
    "        if (eventsCount.c === 0) {",
    "            await db.run(\"INSERT INTO events (name, location, zip_code) VALUES ('Workshop de APF', 'Auditório Principal', '01001-000')\");",
    "            await db.run(\"INSERT INTO events (name, location, zip_code) VALUES ('Semana de Tecnologia 2026', 'Bloco B - Sala 10', '20040-002')\");",
    "            await db.run(\"INSERT INTO events (name, location, zip_code) VALUES ('Simpósio de Node.js', 'Centro de Convenções', '30140-071')\");",
    "        }",
    "        console.log('Banco de dados inicializado/atualizado com sucesso.');",
    "    } catch (err) {",
    "        console.error('Erro ao inicializar BD:', err);",
    "    }",
    "};",
    "initDB();"
].join('\n'));

write('server/src/repositories/EventRepository.ts', [
    "import { getDB } from '../db/database';",
    "export interface Event { id?: number; name: string; location: string; zip_code: string; }",
    "export class EventRepository {",
    "    static async findAll(): Promise<Event[]> {",
    "        const db = await getDB();",
    "        return db.all('SELECT * FROM events ORDER BY id DESC');",
    "    }",
    "    static async create(e: Event): Promise<number> {",
    "        const db = await getDB();",
    "        const result = await db.run('INSERT INTO events (name, location, zip_code) VALUES (?, ?, ?)', [e.name, e.location, e.zip_code]);",
    "        return result.lastID as number;",
    "    }",
    "    static async update(id: number, e: Event): Promise<void> {",
    "        const db = await getDB();",
    "        await db.run('UPDATE events SET name = ?, location = ?, zip_code = ? WHERE id = ?', [e.name, e.location, e.zip_code, id]);",
    "    }",
    "    static async delete(id: number): Promise<void> {",
    "        const db = await getDB();",
    "        await db.run('DELETE FROM events WHERE id = ?', [id]);",
    "    }",
    "}"
].join('\n'));

write('server/src/repositories/ParticipantRepository.ts', [
    "import { getDB } from '../db/database';",
    "export interface Participant { id?: number; name: string; cpf: string; email: string; event_id: number; event_name?: string; }",
    "export class ParticipantRepository {",
    "    static async findAll(): Promise<Participant[]> {",
    "        const db = await getDB();",
    "        return db.all(`SELECT p.*, e.name as event_name FROM participants p LEFT JOIN events e ON p.event_id = e.id ORDER BY p.id DESC`);",
    "    }",
    "    static async create(p: Participant): Promise<number> {",
    "        const db = await getDB();",
    "        const result = await db.run('INSERT INTO participants (name, cpf, email, event_id) VALUES (?, ?, ?, ?)', [p.name, p.cpf, p.email, p.event_id]);",
    "        return result.lastID as number;",
    "    }",
    "    static async update(id: number, p: Participant): Promise<void> {",
    "        const db = await getDB();",
    "        await db.run('UPDATE participants SET name = ?, cpf = ?, email = ?, event_id = ? WHERE id = ?', [p.name, p.cpf, p.email, p.event_id, id]);",
    "    }",
    "    static async delete(id: number): Promise<void> {",
    "        const db = await getDB();",
    "        await db.run('DELETE FROM participants WHERE id = ?', [id]);",
    "    }",
    "}"
].join('\n'));

write('server/src/routes.ts', [
    "import { Router } from 'express';",
    "import { getDB } from './db/database';",
    "import bcrypt from 'bcryptjs';",
    "import jwt from 'jsonwebtoken';",
    "import { authMiddleware } from './middlewares/authMiddleware';",
    "import { EventRepository } from './repositories/EventRepository';",
    "import { ParticipantRepository } from './repositories/ParticipantRepository';",
    "const router = Router();",
    "// Auth",
    "router.post('/login', async (req, res) => {",
    "    const { email, password } = req.body;",
    "    const db = await getDB();",
    "    const user = await db.get('SELECT * FROM users WHERE email = ?', [email]);",
    "    if (!user || !(await bcrypt.compare(password, user.password))) return res.status(401).json({ error: 'Credenciais inválidas' });",
    "    const token = jwt.sign({ id: user.id }, 'super_secret_key', { expiresIn: '1d' });",
    "    res.json({ token, user: { id: user.id, name: user.name, email: user.email } });",
    "});",
    "// Events",
    "router.get('/events', authMiddleware, async (req, res) => res.json(await EventRepository.findAll()));",
    "router.post('/events', authMiddleware, async (req, res) => {",
    "    try { res.status(201).json({ id: await EventRepository.create(req.body) }); } catch(err) { res.status(500).json({error: 'Erro'}); }",
    "});",
    "router.put('/events/:id', authMiddleware, async (req, res) => {",
    "    await EventRepository.update(Number(req.params.id), req.body); res.sendStatus(204);",
    "});",
    "router.delete('/events/:id', authMiddleware, async (req, res) => {",
    "    await EventRepository.delete(Number(req.params.id)); res.sendStatus(204);",
    "});",
    "// Participants",
    "router.get('/participants', authMiddleware, async (req, res) => res.json(await ParticipantRepository.findAll()));",
    "router.post('/participants', authMiddleware, async (req, res) => {",
    "    try { res.status(201).json({ id: await ParticipantRepository.create(req.body) }); } catch(err) { res.status(500).json({error: 'Erro (CPF Duplicado?)'}); }",
    "});",
    "router.put('/participants/:id', authMiddleware, async (req, res) => {",
    "    await ParticipantRepository.update(Number(req.params.id), req.body); res.sendStatus(204);",
    "});",
    "router.delete('/participants/:id', authMiddleware, async (req, res) => {",
    "    await ParticipantRepository.delete(Number(req.params.id)); res.sendStatus(204);",
    "});",
    "export default router;"
].join('\n'));


// ==========================================================
// FRONTEND UPDATES
// ==========================================================

write('client/src/App.tsx', [
    "import React from 'react';",
    "import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';",
    "import { AuthProvider, useAuth } from './context/AuthContext';",
    "import Login from './pages/Login';",
    "import Dashboard from './pages/Dashboard';",
    "import Events from './pages/Events';",
    "import Participants from './pages/Participants';",
    "const PrivateRoute = ({ children }: { children: React.ReactNode }) => {",
    "    const { token } = useAuth();",
    "    return token ? <>{children}</> : <Navigate to=\"/\" />;",
    "};",
    "export default function App() {",
    "    return (",
    "        <AuthProvider>",
    "            <BrowserRouter>",
    "                <Routes>",
    "                    <Route path=\"/\" element={<Login />} />",
    "                    <Route path=\"/dashboard\" element={<PrivateRoute><Dashboard /></PrivateRoute>} />",
    "                    <Route path=\"/events\" element={<PrivateRoute><Events /></PrivateRoute>} />",
    "                    <Route path=\"/participants\" element={<PrivateRoute><Participants /></PrivateRoute>} />",
    "                </Routes>",
    "            </BrowserRouter>",
    "        </AuthProvider>",
    "    );",
    "}"
].join('\n'));

write('client/src/styles/Pages.module.css', [
    ".container { max-width: 1000px; margin: 2rem auto; padding: 0 1rem; }",
    ".header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; border-bottom: 2px solid #eaeaea; padding-bottom: 1rem; }",
    ".header h2 { color: #2c3e50; }",
    ".btnPrimary { background: #3498db; color: #fff; border: none; padding: 0.5rem 1rem; border-radius: 4px; cursor: pointer; font-weight: bold; margin-left: 0.5rem; }",
    ".btnSecondary { background: #95a5a6; color: #fff; border: none; padding: 0.5rem 1rem; border-radius: 4px; cursor: pointer; font-weight: bold; }",
    ".btnLink { background: none; color: #3498db; border: none; cursor: pointer; font-weight: bold; margin-right: 1rem; }",
    ".btnLinkDanger { background: none; color: #e74c3c; border: none; cursor: pointer; font-weight: bold; }",
    ".table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; }",
    ".table th, .table td { padding: 1rem; text-align: left; border-bottom: 1px solid #eaeaea; }",
    ".table th { background: #f8f9fa; font-weight: 600; color: #333; }",
    ".form { background: #fff; padding: 2rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }",
    ".formGroup { margin-bottom: 1.5rem; }",
    ".formGroup label { display: block; margin-bottom: 0.5rem; font-weight: bold; color: #333; }",
    ".formGroup input, .formGroup select { width: 100%; padding: 0.75rem; border: 1px solid #ccc; border-radius: 4px; font-size: 1rem; }",
    ".formActions { display: flex; justify-content: flex-end; gap: 1rem; margin-top: 2rem; }",
    ".cardsContainer { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }",
    ".menuCard { background: #fff; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); cursor: pointer; transition: transform 0.2s; text-align: center; border-top: 4px solid #3498db; }",
    ".menuCard:hover { transform: translateY(-5px); }",
    ".menuCard h3 { margin-bottom: 1rem; color: #2c3e50; }",
    ".menuCard p { color: #666; }"
].join('\n'));

write('client/src/pages/Dashboard.tsx', [
    "import React from 'react';",
    "import { useAuth } from '../context/AuthContext';",
    "import { useNavigate } from 'react-router-dom';",
    "import styles from '../styles/Pages.module.css';",
    "export default function Dashboard() {",
    "    const { logout } = useAuth();",
    "    const navigate = useNavigate();",
    "    return (",
    "        <div className={styles.container}>",
    "            <div className={styles.header}>",
    "                <h2>Sistema Eventify - Menu Principal</h2>",
    "                <button className={styles.btnLinkDanger} onClick={logout}>Sair do Sistema</button>",
    "            </div>",
    "            <div className={styles.cardsContainer}>",
    "                <div className={styles.menuCard} onClick={() => navigate('/events')}>",
    "                    <h3>Manter Eventos</h3>",
    "                    <p>Gestão completa de eventos (CRUD). Busca automática de CEP via API ViaCEP.</p>",
    "                </div>",
    "                <div className={styles.menuCard} onClick={() => navigate('/participants')}>",
    "                    <h3>Manter Participantes</h3>",
    "                    <p>Gestão e Inscrição em Eventos. Validação rígida e matemática de CPF.</p>",
    "                </div>",
    "            </div>",
    "        </div>",
    "    );",
    "}"
].join('\n'));

write('client/src/pages/Events.tsx', [
    "import React, { useEffect, useState } from 'react';",
    "import { useAuth } from '../context/AuthContext';",
    "import { useNavigate } from 'react-router-dom';",
    "import styles from '../styles/Pages.module.css';",
    "export default function Events() {",
    "    const { token } = useAuth();",
    "    const navigate = useNavigate();",
    "    const [events, setEvents] = useState([]);",
    "    const [view, setView] = useState('list');",
    "    const [formData, setFormData] = useState({ id: null, name: '', location: '', zip_code: '' });",
    "    const loadEvents = async () => {",
    "        const res = await fetch('http://localhost:3001/api/events', { headers: { 'Authorization': 'Bearer ' + token } });",
    "        setEvents(await res.json());",
    "    };",
    "    useEffect(() => { loadEvents(); }, []);",
    "    const handleCepBlur = async (e: any) => {",
    "        const cep = e.target.value.replace(/\\D/g, '');",
    "        if (cep.length === 8) {",
    "            try {",
    "                const res = await fetch(`https://viacep.com.br/ws/${cep}/json/`);",
    "                const data = await res.json();",
    "                if (!data.erro) setFormData({ ...formData, location: `${data.logradouro}, ${data.bairro} - ${data.localidade}/${data.uf}` });",
    "            } catch (err) {}",
    "        }",
    "    };",
    "    const handleSubmit = async (e: any) => {",
    "        e.preventDefault();",
    "        const method = formData.id ? 'PUT' : 'POST';",
    "        const url = formData.id ? `http://localhost:3001/api/events/${formData.id}` : 'http://localhost:3001/api/events';",
    "        await fetch(url, { method, headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token }, body: JSON.stringify(formData) });",
    "        setView('list'); loadEvents();",
    "    };",
    "    const handleDelete = async (id: number) => {",
    "        if(window.confirm('Tem certeza que deseja excluir este evento?')) {",
    "            await fetch(`http://localhost:3001/api/events/${id}`, { method: 'DELETE', headers: { 'Authorization': 'Bearer ' + token } });",
    "            loadEvents();",
    "        }",
    "    };",
    "    return (",
    "        <div className={styles.container}>",
    "            <div className={styles.header}>",
    "                <h2>Gestão de Eventos</h2>",
    "                <div>",
    "                    <button onClick={() => navigate('/dashboard')} className={styles.btnSecondary}>Voltar</button>",
    "                    {view === 'list' && <button onClick={() => { setFormData({ id: null, name: '', location: '', zip_code: '' }); setView('form'); }} className={styles.btnPrimary}>Novo Evento</button>}",
    "                </div>",
    "            </div>",
    "            {view === 'list' ? (",
    "                <table className={styles.table}>",
    "                    <thead><tr><th>ID</th><th>Nome</th><th>CEP</th><th>Local (ViaCEP)</th><th>Ações</th></tr></thead>",
    "                    <tbody>",
    "                        {events.map((ev: any) => (",
    "                            <tr key={ev.id}>",
    "                                <td>{ev.id}</td><td>{ev.name}</td><td>{ev.zip_code}</td><td>{ev.location}</td>",
    "                                <td>",
    "                                    <button onClick={() => { setFormData(ev); setView('form'); }} className={styles.btnLink}>Editar</button>",
    "                                    <button onClick={() => handleDelete(ev.id)} className={styles.btnLinkDanger}>Excluir</button>",
    "                                </td>",
    "                            </tr>",
    "                        ))}",
    "                    </tbody>",
    "                </table>",
    "            ) : (",
    "                <form onSubmit={handleSubmit} className={styles.form}>",
    "                    <div className={styles.formGroup}><label>Nome do Evento</label><input required value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} /></div>",
    "                    <div className={styles.formGroup}><label>CEP (Digite e saia do campo para buscar)</label><input required value={formData.zip_code} onBlur={handleCepBlur} onChange={e => setFormData({...formData, zip_code: e.target.value})} /></div>",
    "                    <div className={styles.formGroup}><label>Local</label><input required value={formData.location} onChange={e => setFormData({...formData, location: e.target.value})} /></div>",
    "                    <div className={styles.formActions}>",
    "                        <button type=\"button\" onClick={() => setView('list')} className={styles.btnSecondary}>Cancelar</button>",
    "                        <button type=\"submit\" className={styles.btnPrimary}>Salvar Evento</button>",
    "                    </div>",
    "                </form>",
    "            )}",
    "        </div>",
    "    );",
    "}"
].join('\n'));

write('client/src/pages/Participants.tsx', [
    "import React, { useEffect, useState } from 'react';",
    "import { useAuth } from '../context/AuthContext';",
    "import { useNavigate } from 'react-router-dom';",
    "import styles from '../styles/Pages.module.css';",
    "const isValidCPF = (cpf: string) => {",
    "    cpf = cpf.replace(/[^\\d]+/g, '');",
    "    if(cpf.length !== 11 || /^(\\d)\\1{10}$/.test(cpf)) return false;",
    "    let add = 0; for (let i = 0; i < 9; i ++) add += parseInt(cpf.charAt(i)) * (10 - i);",
    "    let rev = 11 - (add % 11); if (rev === 10 || rev === 11) rev = 0; if (rev !== parseInt(cpf.charAt(9))) return false;",
    "    add = 0; for (let i = 0; i < 10; i ++) add += parseInt(cpf.charAt(i)) * (11 - i);",
    "    rev = 11 - (add % 11); if (rev === 10 || rev === 11) rev = 0;",
    "    return rev === parseInt(cpf.charAt(10));",
    "};",
    "export default function Participants() {",
    "    const { token } = useAuth();",
    "    const navigate = useNavigate();",
    "    const [participants, setParticipants] = useState([]);",
    "    const [events, setEvents] = useState([]);",
    "    const [view, setView] = useState('list');",
    "    const [formData, setFormData] = useState({ id: null, name: '', cpf: '', email: '', event_id: '' });",
    "    const loadData = async () => {",
    "        const pRes = await fetch('http://localhost:3001/api/participants', { headers: { 'Authorization': 'Bearer ' + token } });",
    "        setParticipants(await pRes.json());",
    "        const eRes = await fetch('http://localhost:3001/api/events', { headers: { 'Authorization': 'Bearer ' + token } });",
    "        setEvents(await eRes.json());",
    "    };",
    "    useEffect(() => { loadData(); }, []);",
    "    const handleSubmit = async (e: any) => {",
    "        e.preventDefault();",
    "        if(!isValidCPF(formData.cpf)) return alert('CPF Inválido! A validação algorítmica falhou.');",
    "        if(!formData.event_id) return alert('Selecione um evento para inscrever o participante.');",
    "        const method = formData.id ? 'PUT' : 'POST';",
    "        const url = formData.id ? `http://localhost:3001/api/participants/${formData.id}` : 'http://localhost:3001/api/participants';",
    "        const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token }, body: JSON.stringify(formData) });",
    "        if(!res.ok) return alert('Erro ao salvar participante. Verifique se o CPF já está cadastrado.');",
    "        setView('list'); loadData();",
    "    };",
    "    const handleDelete = async (id: number) => {",
    "        if(window.confirm('Excluir participante?')) {",
    "            await fetch(`http://localhost:3001/api/participants/${id}`, { method: 'DELETE', headers: { 'Authorization': 'Bearer ' + token } });",
    "            loadData();",
    "        }",
    "    };",
    "    return (",
    "        <div className={styles.container}>",
    "            <div className={styles.header}>",
    "                <h2>Gestão de Participantes</h2>",
    "                <div>",
    "                    <button onClick={() => navigate('/dashboard')} className={styles.btnSecondary}>Voltar</button>",
    "                    {view === 'list' && <button onClick={() => { setFormData({ id: null, name: '', cpf: '', email: '', event_id: '' }); setView('form'); }} className={styles.btnPrimary}>Novo Participante</button>}",
    "                </div>",
    "            </div>",
    "            {view === 'list' ? (",
    "                <table className={styles.table}>",
    "                    <thead><tr><th>Nome</th><th>CPF</th><th>E-mail</th><th>Evento Alocado</th><th>Ações</th></tr></thead>",
    "                    <tbody>",
    "                        {participants.map((p: any) => (",
    "                            <tr key={p.id}>",
    "                                <td>{p.name}</td><td>{p.cpf}</td><td>{p.email}</td><td>{p.event_name}</td>",
    "                                <td>",
    "                                    <button onClick={() => { setFormData(p); setView('form'); }} className={styles.btnLink}>Editar</button>",
    "                                    <button onClick={() => handleDelete(p.id)} className={styles.btnLinkDanger}>Excluir</button>",
    "                                </td>",
    "                            </tr>",
    "                        ))}",
    "                    </tbody>",
    "                </table>",
    "            ) : (",
    "                <form onSubmit={handleSubmit} className={styles.form}>",
    "                    <div className={styles.formGroup}><label>Nome Completo</label><input required value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} /></div>",
    "                    <div className={styles.formGroup}><label>CPF (Apenas números)</label><input required value={formData.cpf} onChange={e => setFormData({...formData, cpf: e.target.value})} /></div>",
    "                    <div className={styles.formGroup}><label>E-mail</label><input required type=\"email\" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} /></div>",
    "                    <div className={styles.formGroup}>",
    "                        <label>Inscrever no Evento</label>",
    "                        <select required value={formData.event_id} onChange={e => setFormData({...formData, event_id: e.target.value})}>",
    "                            <option value=\"\">-- Selecione um Evento --</option>",
    "                            {events.map((ev: any) => (<option key={ev.id} value={ev.id}>{ev.name}</option>))}",
    "                        </select>",
    "                    </div>",
    "                    <div className={styles.formActions}>",
    "                        <button type=\"button\" onClick={() => setView('list')} className={styles.btnSecondary}>Cancelar</button>",
    "                        <button type=\"submit\" className={styles.btnPrimary}>Salvar Participante</button>",
    "                    </div>",
    "                </form>",
    "            )}",
    "        </div>",
    "    );",
    "}"
].join('\n'));

console.log('Arquivos atualizados com sucesso!');
